version: '3'

services:

  server:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine3.17
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    env_file:
    - .env.dev

volumes:
  pgdata: